Update pypi.yml

diff --git a/.github/workflows/pypi.yml b/.github/workflows/pypi.yml
--- a/.github/workflows/pypi.yml
+++ b/.github/workflows/pypi.yml
@@ -13,7 +13,7 @@ jobs:
   linux-build:
     strategy:
       matrix:
-        pyver: [py38, py39, py310, py311, py312]
+        pyver: [py310]
     runs-on: ubuntu-latest
     env:
       PYTHON_VERSION: ${{ matrix.pyver }}
@@ -45,78 +45,71 @@ jobs:
           sed -i 's/docker run --rm -it/docker run --rm/g' builder/manywheel/build_wheel.sh
           bash builder/manywheel/build_wheel.sh ${PYTHON_VERSION} ${PLAT_NAME} ${DOCKER_TAG} ${OUTPUT_FOLDER}
       - name: Upload Artifacts
-        uses: actions/upload-artifact@v4
+        uses: actions/upload-artifact@v3
         with:
           if-no-files-found: error
           path: builder/manywheel/${{ env.OUTPUT_FOLDER }}/*
           retention-days: 1
-          name: linux-${{ matrix.pyver }}
 
-  windows-build:
-    strategy:
-      matrix:
-        pyver: ['3.8', '3.9', '3.10', '3.11', '3.12']
-    runs-on: windows-latest
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v3
-      - name: Set up python
-        uses: actions/setup-python@v4
-        with:
-          python-version: ${{ matrix.pyver }}
-      - name: Install python packages
-        run: |
-          pip install -r requirements/build.txt
-          pip install wheel
-      - name: Setup CUDA Toolkit
-        id: cuda-toolkit
-        shell: pwsh
-        run: ./builder/windows/setup_cuda.ps1
-        env:
-            INPUT_CUDA_VERSION: '12.1.0'
-      - name: Build wheel
-        run: |
-          mkdir build
-          cd build
-          # https://github.com/pypa/setuptools/issues/1631
-          pip install -U setuptools
-          ..\builder\windows\generate.ps1
-          cmake --build . --config Release -- /m /v:q
-          if (-Not $?) {
-            echo "build failed"
-            exit 1
-          }
-          cmake --install . --config Release
-          cd ..
-          rm build -Force -Recurse
-          python setup.py bdist_wheel -d build/wheel
-      - name: Upload Artifacts
-        uses: actions/upload-artifact@v4
-        with:
-          if-no-files-found: error
-          path: build/wheel/*
-          retention-days: 1
-          name: windows-${{ matrix.pyver }}
+  # windows-build:
+  #   strategy:
+  #     matrix:
+  #       pyver: ['3.8', '3.9', '3.10', '3.11', '3.12']
+  #   runs-on: windows-latest
+  #   steps:
+  #     - name: Checkout repository
+  #       uses: actions/checkout@v3
+  #     - name: Set up python
+  #       uses: actions/setup-python@v4
+  #       with:
+  #         python-version: ${{ matrix.pyver }}
+  #     - name: Install python packages
+  #       run: |
+  #         pip install pybind11 wheel
+  #     - uses: Jimver/cuda-toolkit@v0.2.11
+  #       id: cuda-toolkit
+  #       with:
+  #         cuda: '12.1.0'
+  #         use-github-cache: false
+  #     - name: Build wheel
+  #       run: |
+  #         mkdir build
+  #         cd build
+  #         # https://github.com/pypa/setuptools/issues/1631
+  #         pip install -U setuptools
+  #         ..\builder\windows\generate.ps1
+  #         cmake --build . --config Release -- /m /v:q
+  #         if (-Not $?) {
+  #           echo "build failed"
+  #           exit 1
+  #         }
+  #         cmake --install . --config Release
+  #         cd ..
+  #         rm build -Force -Recurse
+  #         python setup.py bdist_wheel -d build/wheel
+  #     - name: Upload Artifacts
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         if-no-files-found: error
+  #         path: build/wheel/*
+  #         retention-days: 1
 
-  publish:
-    runs-on: ubuntu-latest
-    environment: 'prod'
-    needs:
-      - linux-build
-      - windows-build
-    steps:
-      - name: Download artifacts
-        uses: actions/download-artifact@v4
-        with:
-          path: artifact
-          merge-multiple: true
-      - name: Display artifacts
-        run: ls artifact/ -lh
-      - name: Set up python3.8
-        uses: actions/setup-python@v4
-        with:
-          python-version: '3.8'
-      - name: Upload to pypi
-        run: |
-          pip install twine
-          twine upload artifact/* -u __token__ -p ${{ secrets.pypi_password }}
+  # publish:
+  #   runs-on: ubuntu-latest
+  #   environment: 'prod'
+  #   needs:
+  #     - linux-build
+  #     - windows-build
+  #   steps:
+  #     - name: Download artifacts
+  #       uses: actions/download-artifact@v3
+  #     - name: Display artifacts
+  #       run: ls artifact/ -lh
+  #     - name: Set up python3.8
+  #       uses: actions/setup-python@v4
+  #       with:
+  #         python-version: '3.8'
+  #     - name: Upload to pypi
+  #       run: |
+  #         pip install twine
+  #         twine upload artifact/* -u __token__ -p ${{ secrets.pypi_password }}
